### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hi,

This PR will fix : 

- 1 typo in `CONTRIBUTING.md`
- 1 typo in `docs/private-registries.md`
- 3 typos in `scripts/lifecycle-tests.sh`

Cheers! :robot:

### CODE REVIEW

**Review by piksel — APPROVED** [review]

**Comment by simonaronsson** [comment]
@all-contributors add @pgrimaud for docs

**Comment by piksel** [comment]
@simskij do you know why the greeting failed?

**Comment by zoispag** [comment]
@piksel it always fails 😞

**Comment by zoispag** [comment]
Here's why: https://github.com/actions/first-interaction/issues/10#issuecomment-545576314

**Comment by piksel** [comment]
Oh wow. That's a bummer.

**Comment by simonaronsson** [comment]
It works on issues though, so maybe we could filter it to that for the time being.

**Pull request merged**
