### PR TITLE
fix: set correct URL for codacy badge

### LINKED ISSUE #762: Codacy badge is broken on GH Pages
**Describe the bug**
The Codacy badge is broken on gh-pages branch

**To Reproduce**
1. Go to https://containrrr.dev/watchtower/
2. Scroll down to badges
4. See error that the badge throws 404

**Expected behavior**
All the badges should work

### PR DESCRIPTION
**Pull request by DaxServer**
Fix #762

### CODE REVIEW

**Review by zoispag — APPROVED** [review]

**Comment by simonaronsson** [comment]
Thank you for your contribution! 🙏🏼

The GH Pages are generated from main on release. It was also changed in main through commit https://github.com/containrrr/watchtower/commit/5b349e5dc4b7bca18bf6b548f7bf317821e444dd.

Would you mind retargeting the PR against main and check if there are inconsistencies with the root readme that should be carried over to the docs one?

Thanks again,
Simme

**Review by simonaronsson — CHANGES_REQUESTED** [review]
See comment

**Comment by DaxServer** [comment]
It looks like I can't change the fork's head from `SrihariThalla:gh-pages` to `SrihariThalla:main`. Shall I simply close this one and create a new PR?

**Comment by piksel** [comment]
No, even if that would be possible they don't share a common root branch, so the diff would be *everything* basically. And I guess git doesn't even allow you to do that. Easier to just create a new one @SrihariThalla

**Comment by DaxServer** [comment]
Created #764

**Pull request closed without merging**
