### PR TITLE
Implement pre/post-update command feature

### PR DESCRIPTION
**Pull request by alexandremenif**
This pull request introduces the possibility to specify pre and post update commands to a container managed by watchtower.

Watchtower will execute the pre-update command before stopping the container, and execute the post-update command after restarting it. The pre and post commands are both specified as labels on the target container. ~~As indicated in the `README.md` file, the commands are formatted as JSON strings.~~

This is the feature that I have already described in [this issue](https://github.com/v2tec/watchtower/issues/183)

A possible use case for this feature is to use watchtower to update containers based on the official postgres image. These containers need to migrate their data when the database server is updated from one major version to another. This migration can be performed using a pre-update command to dump the data into a persistent file and with a post-update command to restore the data from the file to the database server.

### CODE REVIEW

**Comment by alexandremenif** [comment]
I have added a commit to specify the commands as simple strings instead of JSON formatted strings.

**Comment by ChessSpider** [comment]
Awesome. I hope this gets merged soon.

**Comment by ChessSpider** [comment]
I'm not an expert.
But, maybe someone finds this useful:

```
FROM golang:alpine as builder
RUN apk update && apk add  alpine-sdk ca-certificates tzdata
RUN curl https://glide.sh/get | sh

RUN go get github.com/v2tec/watchtower; exit 0

WORKDIR /go/src/github.com/v2tec/watchtower

RUN git remote set-url origin  git://github.com/alexandremenif/watchtower.git && git fetch  && git checkout pre-post-update-command

RUN glide install

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM scratch

LABEL "com.centurylinklabs.watchtower"="true"

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /go/src/github.com/v2tec/watchtower/watchtower /watchtower

ENTRYPOINT ["/watchtower"]
```

**Comment by ChessSpider** [comment]
Uhm @alexandremenif Do your additions work?
I just get 
```
watchtower_1  | time="2018-06-26T09:31:56Z" level=info msg="Executing pre-update command." 
watchtower_1  | time="2018-06-26T09:31:57Z" level=error msg="Command exited with code 127." 
```
for everything? Including a simple shell script like 
```
root@backend:/srv/docker/someservice# cat test.sh 
#!/bin/bash

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

echo "running" > /srv/docker/someservice/time.txt
echo `date` >> /srv/docker/someservice/time.txt
```

Isn't your code additions trying to run ``sh`` inside the watchtower container? Where both ``sh`` does not exists and the path i set in ``com.centurylinklabs.watchtower.pre-update-command`` is not available? 

I do not seem to be able to get it to work.

**Comment by alexandremenif** [comment]
Hello @ChessSpider, 

The command is supposed to be executed on the container that is being updated, not in the watchtower container. I see your script `test.sh` is using `bash`, does your image support it? For example alpine-based images only have `sh`. What image are you using?

**Comment by ChessSpider** [comment]
Ah cool. That wasn't clear to me! Thanks for the feedback 👍

**Comment by lephleg** [comment]
What's the progress on this? I'm really interested in integrating it. 
Do you require any help?

**Comment by mote0230** [comment]
Does someone have a fork with this in the docker repo?

**Comment by Freekers** [comment]
> 
> 
> What's the progress on this? I'm really interested in integrating it.
> Do you require any help?

According to the automated code review, it's stuck on:

`comment on exported method Container.PreUpdateCommandInfo should be of the form "PreUpdateCommandInfo ..."`

If the code review passes, it should automatically be merged if I understand correctly.

**Comment by alexandremenif** [comment]
@Freekers I did update the code some months ago to address this, and my impression is that this review comment is not relevant anymore (the function has been renamed to match the comment). I think the PR is still open because we need someone with write access on watchtower to approve it.

**Comment by Freekers** [comment]
> 
> 
> @Freekers I did update the code some months ago to address this, and my impression is that this review comment is not relevant anymore (the function has been renamed to match the comment). I think the PR is still open because we need someone with write access on watchtower to approve it.

Okay, well let's try pinging @stffabi @huddlesj @napstr @darknode @Robotex @fomk @mxschmitt 
Can you guys help merging this one, pretty please :) ?
Thank you very much!

**Comment by darknode** [comment]
Hi!

@alexandremenif Thanks for your idea and contribution! I would like to add some suggestions, it would be great if you add into the documentation section that:
1. Commands will be executed inside a container
2. "Command" means sh script
3. Behavior of the watchtower if commands were executed with errors
4. Warning that labels could be inherited from base images, so in some cases unwanted commands might be executed ([Docker labels](https://docs.docker.com/engine/reference/builder/#label))

Also I would disable this feature by default(because of p4) and add flag to watchtower configuration, which enables it. _And please try to run go fmt, it looks like some code is unformatted properly, sorry if I'm wrong and it's a but of github differ._

**Comment by alexandremenif** [comment]
@darknode I have made some changes to address your points.

Also, while testing with labels defined in a Dockerfile, I discovered that the label for the *post-update* command was erased from the container object as a "side-effect" of the `runtimeConfig()` method called when restarting the container. I have addressed this issue at my level, to make the *post-update* command mechanism work, but maybe we could consider rewritting the method `runtimeConfig()` to make it side-effect free.

**Comment by darknode** [comment]
Hi @alexandremenif!
I'm sorry for the late reply. I've prepared some "integration-tests" to check if commands work properly. Tests implemented as bash script, which you can find [here as a gist](https://gist.github.com/darknode/161c1231fdd77996ab84e7999042c951). You can change DEFAULT_WATCHTOWER variable to a path of your watchtower executable. More details you can find inside. In general it tests commands from base image of container, and commands from container.
Also I've checked `runtimeConfig()` and it works as expected. To get little bit better way of commands handling I did some changes and attach them as a git patch 
[Refactor-pre-post-update-commands.patch.gz](https://github.com/v2tec/watchtower/files/2536008/Refactor-pre-post-update-commands.patch.gz). You can apply it on your branch with command `git am < Refactor-pre-post-update-commands.patch`

To have a full solution I think we need to handle case with linked containers better. Example: container `server` has linked container `db`, `db` has commands, watchtower find newer image for `server` and restarts both `server` and `db`, because they are linked. So commands are executed on `db`, but `db` doesn't really have an updated image.
So I'm trying to figure out how to handle this. I hope I should have a "fix" in a few days.

**Comment by alexandremenif** [comment]
Hello @darknode 

Thanks a lot for the patch and the script.
I have applied the patch on this branch.
I have also committed your test script, since I find it very useful (I had a similar one, but much less elaborated). I have only made some changes to use GOPATH in the executable path, and to output the files required to build the image into a temporary directory.

**Review by darknode — APPROVED** [review]
LGTM

**Comment by alexandremenif** [comment]
I think we still need to address how to handle linked containers. I think that we could simply replace the `Stale` boolean property on containers with a 3 valued status (update/restart/none) to distinguish the different cases. I will try to provide an implementation for this in the coming days.

**Comment by alexandremenif** [comment]
I have added an additional commit to handle the case of linked containers: pre/post update commands will only be executed on containers with outdated images, not on linked containers.

**Comment by itsthejb** [comment]
Hey there,

This is great, and I'm definitely looking to using this (sadly, by having to merge to my own fork). Idea/suggestion; it appears that this currently only allows executing a command for the _updated_ containers. My particular use case would be to execute a command from the watchtower container whenever any image is updated - with is restarting my reverse proxy. Therefore, could this be extended to allow setting the command label on the watchtower container itself?

**Comment by alexandremenif** [comment]
> Hey there,
> 
> This is great, and I'm definitely looking to using this (sadly, by having to merge to my own fork). Idea/suggestion; it appears that this currently only allows executing a command for the _updated_ containers. My particular use case would be to execute a command from the watchtower container whenever any image is updated - with is restarting my reverse proxy. Therefore, could this be extended to allow setting the command label on the watchtower container itself?

Hello @itsthejb, and thank you for your interest. Unfortunately I no longer use watchtower and therefore I have lost interest in developing this feature further.

I guess that it would be nice to have it merged, since some people are still interested in it. It still lack a final review though. Maybe @darknode could have a last look?

**Comment by Freekers** [comment]
@alexandremenif Have you switched to an alternative for Watchtower or have you stopped automatically updating your Docker containers?

@itsthejb Thanks for pushing/publishing your fork to Docker Hub, I'm looking forward to use it. One question regarding the location of the post/pre update scripts; should these be relative to the Docker container or to the Docker host?

**Comment by itsthejb** [comment]
@Freekers I'm afraid I haven't really tested it, since I'm not sure it currently has the feature I'm looking for. Don't know Go so seems a bit unlikely I'll be trying it...

**Comment by simonaronsson** [comment]
Lots of solid work here! I'll have a look at it and try to figure out whether it's ready to be merged.

**Comment by Redsandro** [comment]
Is it possible to run a command in stead of a shell script?

Examples:

* `LABEL (...).pre-update-command="gitlab-rake gitlab:backup:create"`
* `LABEL (...).pre-update-command="mongodump -o /mnt/share/backup"`

This would remove the hassle of deploying and mounting external `.sh` files to containers.

**Comment by alexandremenif** [comment]
> Is it possible to run a command in stead of a shell script?
> 
> Examples:
> 
> * `LABEL (...).pre-update-command="gitlab-rake gitlab:backup:create"`
> * `LABEL (...).pre-update-command="mongodump -o /mnt/share/backup"`
> 
> This would remove the hassle of deploying and mounting external `.sh` files to containers.

Any command executable with `sh` in the container should work.

**Pull request closed without merging**
