### PR TITLE
Add a warning about using Watchtower in production

### PR DESCRIPTION
**Pull request by simonaronsson**
Add a warning about using Watchtower in production, and a couple of recommended alternatives.

### CODE REVIEW

**Comment by waja** [comment]
How about also declare that also on https://containrrr.dev/watchtower/?
Beside that, is there a special reason for this warning?

**Comment by simonaronsson** [comment]
> How about also declare that also on https://containrrr.dev/watchtower/? Beside that, is there a special reason for this warning?

That will end up on the docs next time we cut a release. The reason is mainly setting expectations. Blindly updating containers is usually not a good practice in a setting where data consistency and reliability is required.

Historically, we've avoided making a stance either way, but in the light of the latest update spawning clones of watchtower itself, I felt a warning was in place so that users can make an informed, conscious choice about what risk levels they are willing to tolerate.

**Comment by waja** [comment]
Yeah ... but everybody following `latest` (for example) in any way might be on the risky side and this is not an issue of watchtower but on using a moving target.
We are using watchtower for the most time to follow a "release"-tag ... for example for mariadb you can follow `lts` or what ever [tag](https://hub.docker.com/_/mariadb) you trust to follow. We use the x.y tags in this case. :)

**Comment by piksel** [comment]
It still may be the case that the update leaves your environment broken. Watchtower tries its best to recreate containers using the same configuration, but there is always a possibility that the update fails and you're left without a running container (since we have to remove the old container before creating the new one). I do however agree with the notion of not telling people how they *should* (not) be using watchtower, but rather inform about what the consequences may be. Perhaps encouraging that you can create your containers from scratch for example, and keeping the valuable state in volumes etc.

**Pull request merged**
