### PR TITLE
docs: add note about docker hub private images

### PR DESCRIPTION
**Pull request by piksel**
Add findings in https://github.com/containrrr/watchtower/issues/796#issuecomment-967132551 to docs.

### CODE REVIEW

**Comment by dschmidt** [comment]
I can not confirm this. For me only docker.io in image name and config.json worked. This did not.

**Comment by piksel** [comment]
@dschmidt Could you post the `--debug` lines corresponding these:
```
DEBU[0004] Trying to load authentication credentials.    container=/wt-test2 image="index.docker.io/piksel/wt-test:latest"
DEBU[0004] Loaded auth credentials for user piksel, on registry index.docker.io/piksel/wt-test:latest, from file /config.json
```
?

And the contents of your `config.json` (with the actual credentials removed of course).

**Comment by dschmidt** [comment]
Of course, happy to :)

This **works**:
```
watchtower_1         | time="2021-11-16T20:05:48Z" level=debug msg="Trying to load authentication credentials." container=/examples_projectxyz_1 image="docker.io/userxyz/projectxyz:tagxyz"
watchtower_1         | time="2021-11-16T20:05:48Z" level=debug msg="Loaded auth credentials for user userxyz, on registry docker.io/userxyz/projectxyz:tagxyz, from file /config/config.json"
``` 
with
```
{
        "auths": {
                "https://docker.io": {
                        "auth": "...."
                }
        }
}
```
and
```
  projectxyz:
    image: docker.io/userxyz/projectxyz:tagxyz
```

Actually this seems to work as well, although I was pretty sure I had tested it and it didn't work ... anyhow this seems to **work** actually:
```
watchtower_1         | time="2021-11-16T20:14:27Z" level=debug msg="Trying to load authentication credentials." container=/examples_nodered_1 image="index.docker.io/userxyz/projectxyz:tagxyz"
watchtower_1         | time="2021-11-16T20:14:27Z" level=debug msg="Loaded auth credentials for user userxyz, on registry index.docker.io/userxyz/projectxyz:tagxyz, from file /config/config.json"
```

with
```
  projectxyz:
    image: index.docker.io/userxyz/projectxyz:tagxyz
```

``` 
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "..."
                }
        }
}
```
which is what I get when simply logging in with `docker login`.


So false alarm, I think you are right. I'm just not sure this documentation actually helps, as this information is basically already available from https://github.com/containrrr/watchtower/blob/f81d0b17c19e6b885884ce2f94a3aab76e258e88/docs/private-registries.md#share-the-docker-configuration-file.
I for some reason just failed to apply it correctly, maybe because I somehow messed up reloading after making changes...

**Comment by piksel** [comment]
Do you mean the prefix in the docker compose for watchtower? I don't see anything that expressively tells you to add it to your other containers... right?

**Review by simonaronsson — APPROVED** [review]

**Pull request merged**
