### PR TITLE
add slack notification cli flag

### PR DESCRIPTION
**Pull request by ubergesundheit**
This pull request adds sending of notifications to slack channels.

Please review the glide.yaml and glide.lock files

### CODE REVIEW

**Comment by rdamazio** [comment]
This app already uses logrus which can be hooked to slack - why not just use that? (unfortunately that doesn't work for email, since logrus email integration only sends errors)

**Comment by Nightbr** [comment]
Hey, the idea is pretty cool, I would really enjoy slack notification for watchtower.
If you still want to contribute on this feature, look at amazing work of @rdamazio here https://github.com/v2tec/watchtower/pull/106 and you can try to implement Slack notification with logrus and this integration https://github.com/johntdyer/slackrus

**Comment by stffabi** [comment]
Yeah, would be great to have this included in the same release as the email notifications.

**Comment by ubergesundheit** [comment]
I'll see if I am able to change everything to use logrus/slackrus

**Comment by ubergesundheit** [comment]
See #113

**Pull request closed without merging**
