### PR TITLE
add ghcr.io

### PR DESCRIPTION
**Pull request by ksurl**
PR for https://github.com/containrrr/watchtower/issues/722

## PREREQUISITES  
* create github personal access token with permissions for read/write packages as seen [here](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images)
* add the token as a Circle CI variable named GITHUB_PASS and a GitHub token as GITHUB_PASSWORD
* enable enhanced container support in profile settings (optional?)

## POST MERGE  
* after first build has been published, package needs to be made public (defaults to private)

### CODE REVIEW

**Review by simonaronsson — CHANGES_REQUESTED** [review]
Hey!

Thank you for your contribution! Since the opening of this PR, we've completed the CI move to GitHub Actions. Would you mind updating the PR?

**Comment by ksurl** [comment]
it will probably fail without the repo secrets if they're not already created

GITHUB_USERNAME
GITHUB_USER
GITHUB_PASS

**Comment by ksurl** [comment]
should I reset my branch to before merging from main and only add the new workflow yml files? I didn't realize until after pushing that merging all the files would create a conflict once this is merged later with out of date files from the main branch. I should have only merged locally to check what changed and reset before pushing.

**Comment by ksurl** [comment]
or maybe closing this PR and opening a fresh one with a new local branch in my fork would be cleaner.

**Comment by simonaronsson** [comment]
> or maybe closing this PR and opening a fresh one with a new local branch in my fork would be cleaner.

Yeah, I think so. If you don't mind it would probably be nicer.

> it will probably fail without the repo secrets if they're not already created

Secrets should not really be needed though, right? As it's running in a GitHub action it should get a token from the runner.

**Comment by ksurl** [comment]
The token here is specifically for pushing the image to github. Not accessing the code repo. Similar to requiring a token for docker hub. Since it is connected at the account or org level, not repo, for container images. I'll create a new PR and close this.

**Pull request closed without merging**
