### PR TITLE
Adding basic (but flexible) notification system which hooks into logrus.

### PR DESCRIPTION
**Pull request by rdamazio**
This only adds e-mail notifications, but others could be easily done. In
many cases, adding another existing logrus hook will be sufficient.

### CODE REVIEW

**Comment by stffabi** [comment]
Thanks so much for your contribution, really a nice addition to watchtower. 

I'll take a look into it in the next couple of days.

**Review by cwildfoerster — APPROVED** [review]
LGTM

**Comment by rdamazio** [comment]
cwildfoerster - thanks, but I suspect stffabi or someone else with write access needs to also approve.

**Comment by stffabi** [comment]
@rdamazio thanks, LGTM. Would you have time to add some little documentation to the readme.md?

**Comment by Nightbr** [comment]
hey, nice work!
+1 for more documentation and also it could be great to configure logrus slack integration.

**Comment by rdamazio** [comment]
Done - see if this looks good.

**Comment by stffabi** [comment]
@rdamazio thanks again for your contribution. I'm merging it right now.

**Comment by stffabi** [comment]
@rdamazio great work.

**Review by stffabi — APPROVED** [review]

**Pull request merged**
