### PR TITLE
Update readme to reflect that the project has been abandoned

### PR DESCRIPTION
**Pull request by XanderStrike**

### CODE REVIEW

**Comment by simonaronsson** [comment]
I'm trying to get in touch with the original maintainer to see if it would be possible to take over the maintainer responsibilities. Will post back as I know more

**Comment by XanderStrike** [comment]
There's already this: https://github.com/pyouroboros/ouroboros

They just don't have the SEO to turn up at the top of the search results unfortunately. It took me a while of screwing around with Watchtower to realize documented features don't work. Honestly it'd probably be best to just link to Ouroboros from the readme, but I didn't want to push my luck.

**Comment by XanderStrike** [comment]
Also now that I do a little more research it seems

**Comment by simonaronsson** [comment]
Thats not even the same product or codebase.

**Comment by XanderStrike** [comment]
Correct. It addresses the same need though, and it's actively maintained, which is why I support using that vs trying to resurrect this.

**Comment by simonaronsson** [comment]
I've managed to get a hold of Brian DeHamer, who was one of the original developers. Unfortunately, he doesn't have any access to the repository. As I've been unable to get hold of anyone with write access to the repo I've continued per Brians suggestion and forked the repo.

So, until  development is continued in this repo or I've been able to get access to the repo; a fork will be available on https://github.com/containerized/watchtower where development will (hopefully) be continued. All submissions, suggestions and help is welcome to keep the forked project up and running.

Thanks,
Simon

**Comment by XanderStrike** [comment]
This isn't resolved, the PR was meant to serve as notice that the project is abandoned.

When I'm suspicious of a repo I often check open PRs and issues. With this PR closed there's no notice that this fork is abandoned and no way for users to find your fork.

**Comment by simonaronsson** [comment]
> This isn't resolved, the PR was meant to serve as notice that the project is abandoned.

My bad for not writing a comment. It is resolved as the whole repo has been transferred to a new organization, with the ambition of keeping it maintained. Thanks for the concern, though!

**Comment by XanderStrike** [comment]
Oh wow! I missed the move to the new org.

Hooray!

**Comment by simonaronsson** [comment]
Feel free to chip in if you find any issues where you'd like to contribute! :)

**Pull request closed without merging**
