### PR TITLE
Fix docker-compose syntax in quick-start. GH #1105

### PR DESCRIPTION
**Pull request by atombrella**
Result after my changes. Although the tabbed feature is not working for me locally.

docker-compose-volumes-watchtower

### CODE REVIEW

**Comment by piksel** [comment]
Yeah, this will break the tabs. To preview it locally, you need to serve it using `mkdocs serve` (after installing the `mkdocs-material` theme):
https://squidfunk.github.io/mkdocs-material/getting-started/

I think this was caused by some auto-formatting...

**Comment by atombrella** [comment]
Hmm, not even on `main`, the tabs are working, and some stuff under `node_modules` is not there. I looked in the workflow to see how to test locally for the docs.

**Comment by atombrella** [comment]
```
INFO     -  [11:47:51] Browser connected: http://localhost:8000/watchtower/
WARNING  -  [11:47:52] "GET /node_modules/rxjs/src/internal/Observable.ts HTTP/1.1" code 404
WARNING  -  [11:47:52] "GET /node_modules/rxjs/src/internal/ReplaySubject.ts HTTP/1.1" code 404
INFO     -  [11:47:52] Browser connected: http://127.0.0.1:8000/watchtower/
```

**Comment by piksel** [comment]
Yeah, this is due to:
https://squidfunk.github.io/mkdocs-material/upgrade/#pymdownxtabbed

**Comment by piksel** [comment]
Fixed the config to use the new tabs and added the correct indentation to have them grouped together:
image

**Comment by simonaronsson** [comment]
I'll merge this as it's currently broken, thanks all for your contributions! With that said, I think we should get rid of the tabbed feature as it just makes the docs less digestible in favor of flair. 😅

**Pull request merged**
