### PR TITLE
revert base image to centurylink/ca-certs

### PR DESCRIPTION
**Pull request by frodopwns**
this was accidentally changed to ubuntu by a PR I made

### CODE REVIEW

**Comment by bahlo** [comment]
Can you please also add the `MAINTAINER` and `LABEL` back? See [diff](https://github.com/CenturyLinkLabs/watchtower/pull/13/files#diff-3254677a7917c6c01f55212f86c57fbf).

**Comment by stffabi** [comment]
This PR is outdated and the suggested changes have already been merged into the master through another PR.

**Comment by stffabi** [comment]
Therefore this PR could be closed.

**Comment by stffabi** [comment]
Changes have been already reverted by #26

**Pull request closed without merging**
