### PR TITLE
do not delete same image twice when cleaning up

### PR DESCRIPTION
**Pull request by mindrunner**

### CODE REVIEW

**Review by simonaronsson — CHANGES_REQUESTED** [review]
Thank you very much for the pull request! While this is a much needed change, that actually seem to do what it's supposed to, I'd like to ask you to switch the usage of sets to either a map or slice. [This very short article](https://yourbasic.org/golang/implement-set/) explains how to do this in idiomatic go. Thank you  🙏🏼

**Comment by mindrunner** [comment]
Cool, thanks for the feedback. I wasn't sure about how to use sets in go! Since my computer broke down unexpextedly, I will need some weeks to be productive again. Will adjust the PR as soon as I am back.

**Comment by mindrunner** [comment]
Hi, I updated my PR! Please have a look and let me know what you think! :)

**Comment by simonaronsson** [comment]
> Hi, I updated my PR! Please have a look and let me know what you think! :)

Thank you! Will review it as soon as possible 👍

**Review by simonaronsson — APPROVED** [review]
LGTM

**Comment by simonaronsson** [comment]
@all-contributors add @mindrunner for code

**Pull request merged**
