### PR TITLE
Expand docker.config section

### PR DESCRIPTION
**Pull request by EDIflyer**
Update to documentation to highlight the benefit of doing this if using 2FA on Docker Hub

### CODE REVIEW

**Comment by EDIflyer** [comment]
sorry had renamed my branches so they made more sense, didn't realise that would automatically close the PR!

**Comment by piksel** [comment]
Yeah, you cannot change the source branch, so if the branch is renamed, the PR is automatically closed as the source branch doesn't exist anymore.

**Comment by EDIflyer** [comment]
Thanks, @piksel - live and learn 😂 I've restored those branches and the PRs 👍

**Review by simonaronsson — APPROVED** [review]

**Comment by simonaronsson** [comment]
@all-contributors add @EDIflyer for docs

**Pull request merged**
