### PR TITLE
Update Shoutrrr to v0.4

### LINKED ISSUE #758: Container crashes in 1.1.6 with slack notification enabled
**Describe the bug**
After updating from 1.1.5 to 1.1.6 the container will crash with a seg fault (see below) when slack notifications is enabled.  Going back to 1.1.5 with the exact same config works, and removing the slack notification environment variables in 1.1.6 also works.

**To Reproduce**
Just start the container (v 1.1.6) with slack notification enabled

**Expected behavior**
The container to startup without crashing when slack notification is enabled.

**Environment**
 - Platform  QNAP NAS OS (container station)
 - Architecture  Intel x64
 - Docker version 1.19 (I believe that's the version QNAP runs with)

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/firstoken/secondtoken/thirdtoken
WATCHTOWER_NOTIFICATIONS=slack

```

```
DEBU[0000]                                              

DEBU[0000] Sleeping for a second to ensure the docker api client has been properly initialized. 

DEBU[0001] Retrieving running containers                

DEBU[0001] There are no additional watchtower containers 

DEBU[0001] Watchtower HTTP API skipped.                 

INFO[0001] Starting Watchtower and scheduling first run: 2021-01-11 23:00:00 +0000 UTC 

Failed to send notification via shoutrrr (url=slack://watchtower@firsttoken/secondtoken/thirdtoken):  failed to send using slack: timed out

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xaf26ce]



goroutine 36 [running]:

github.com/containrrr/shoutrrr/pkg/services/slack.(*Service).doSend(0xc000375060, 0xc0003d6a80, 0xc000443bd0, 0x4c, 0x0, 0x0)

	/go/pkg/mod/github.com/containrrr/shoutrrr@v0.3.0/pkg/services/slack/slack.go:57 +0x1ae

github.com/containrrr/shoutrrr/pkg/services/slack.(*Service).Send(0xc000375060, 0xc000443bd0, 0x4c, 0xc0000a20a8, 0x0, 0x0)

	/go/pkg/mod/github.com/containrrr/shoutrrr@v0.3.0/pkg/services/slack/slack.go:38 +0xdf

github.com/containrrr/shoutrrr/pkg/router.sendToService.func1(0xc0000ab440, 0xd92cc0, 0xc000375060, 0xc000443bd0, 0x4c, 0xc0000a20a8)

	/go/pkg/mod/github.com/containrrr/shoutrrr@v0.3.0/pkg/router/router.go:85 +0x4f

created by github.com/containrrr/shoutrrr/pkg/router.sendToService

	/go/pkg/mod/github.com/containrrr/shoutrrr@v0.3.0/pkg/router/router.go:85 +0x1a5

```

</details>

**Additional context**
Note even in previous releases it always give me the timeout error for slack notifications at startup but then subsequent notifications worked fine.

### LINKED ISSUE #761: "Shoutrrr notification" Title when notifying with Gotify
**Describe the bug**
As of 1.1.6, Watchtower notifications are being sent to gotify with a title of "Shoutrrr notification" rather than "Watchtower" intermittently.

**To Reproduce**
1. Send notifications to a gotify server

**Expected behavior**
Notifications should have a title of "Watchtower"

**Screenshots**
image

### LINKED ISSUE #767: In v1.1.6, Notifications Fail with Insecure (HTTP) Gotify URL
**Describe the bug**
On v1.1.6, Gotify notifications fail when configured with HTTP URL.

**To Reproduce**
1. Configure Watchtower to send notifications to insecure (HTTP) Gotify URL.
2. Trigger notification
3. Watchtower attempts to send via HTTPS & it fails.

**Expected behavior**
Expectation would be that notifications would be sent to HTTP URL and not HTTPS URL.

**Screenshots**
v1.1.5:
time="2021-01-12T08:41:03-06:00" level=warning msg="Using an HTTP url for Gotify is insecure"
time="2021-01-12T08:41:04-06:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-13 06:15:00 -0600 CST"

v1.1.6:
time="2021-01-12T08:48:40-06:00" level=warning msg="Using an HTTP url for Gotify is insecure"
time="2021-01-12T08:48:41-06:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-13 06:15:00 -0600 CST"
Failed to send notification via shoutrrr (url=gotify://gotify/REMOVED):  failed to send notification to Gotify: Post "https://gotify/message?token=REMOVED": dial tcp 172.21.0.17:443: connect: connection refused

**Environment**
Debian 10
docker-compose version 1.21.0-3
docker.io version 18.09.1+dfsg1-7.1+deb10u2

<details>
 <summary><b> Logs from running watchtower with the <code>--debug</code> option </b></summary>

```
time="2021-01-12T08:56:41-06:00" level=debug
time="2021-01-12T08:56:41-06:00" level=warning msg="Using an HTTP url for Gotify is insecure"
time="2021-01-12T08:56:41-06:00" level=debug msg="Sleeping for a second to ensure the docker api client has been properly initialized."
time="2021-01-12T08:56:42-06:00" level=debug msg="Retrieving running containers"
time="2021-01-12T08:56:42-06:00" level=debug msg="There are no additional watchtower containers"
time="2021-01-12T08:56:42-06:00" level=debug msg="Watchtower HTTP API skipped."
time="2021-01-12T08:56:42-06:00" level=info msg="Starting Watchtower and scheduling first run: 2021-01-13 06:15:00 -0600 CST"
Failed to send notification via shoutrrr (url=gotify://gotify/REMOVED):  failed to send notification to Gotify: Post "https://gotify/message?token=REMOVED": dial tcp 172.21.0.17:443: connect: connection refused
```

</details>

**Additional context**
Downgrading back to v1.1.5 resolves this for now.

### LINKED ISSUE #768: Watchtower 1.1.6 Discord via slack url no long has correct formatting
**Describe the bug**

updated to 1.1.6 and discord notifications no longer display with correct formatting, just plain text. also does not respect custom username and defaults to watchtower

**Expected behavior**

environment variables set and settings working as before

**Screenshots**

working version
image

broken version
image

**Environment**
 - Platform docker
 - Architecture x86
 - Docker version 20.10.2

### LINKED ISSUE #772: v1.1.6 ignores port when sending to Gotify
**Describe the bug**
The port is being ignored when sending notification to Gotify

**Environment**
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:18:13 2020
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:48 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
  `.::///+:/-.        --///+//-:``    pi@raspberrypi
 `+oooooooooooo:   `+oooooooooooo:    --------------
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 4 Model B Rev 1.4
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.4.79-v7l+
     `:++ooo/.        :+ooo+/.`       Uptime: 8 days, 29 mins
        ...`  `.----.` ``..           Packages: 1872 (dpkg)
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/1
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2711 (4) @ 1.500GHz
       .::::::::`  -::::::::` `       Memory: 855MiB / 7874MiB
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`
```

**Logs**

```
Failed to send notification via shoutrrr (url=gotify://192.168.1.175:8188/removed):  
failed to send notification to Gotify: Post "https://192.168.1.175/message?token=removed": 
dial tcp 192.168.1.175:443: connect: connection refused,
```

**Additional context**
Working example using httpie CLI

```
 http -f POST "http://192.168.1.175:8188/message?token=Removed" title="my title" message="my message" priority="5"
HTTP/1.1 200 OK
Content-Length: 114
Content-Type: application/json
Date: Wed, 13 Jan 2021 10:49:48 GMT

{
    "appid": 1,
    "date": "2021-01-13T10:49:48.068486043Z",
    "id": 30,
    "message": "my message",
    "priority": 5,
    "title": "my title"
}

```

### LINKED ISSUE #775: Invalid mail header with new version
**Describe the bug**
It seems that in the latest version (1.1.6) mail sending is somehow broken. Currently, watchtower mails get tagged by my mail server because of a bad mail header.
Error msg:
```
INVALID HEADER
Missing required header field: "Date"
```

I checked the original mail and the Date field is missing

**To Reproduce**
Send mail via watchtower

**Expected behavior**
Well-formed email header

**Environment**
 - x86 and ARM
 - docker current version

### LINKED ISSUE #785: shoutrrr slack notification: message exceeds max length
**Describe the bug**
When trying to send slack notification via shoutrrr (slack webhook api message max length being 40,000 chars) where the notification is ~1700 chars, I get the error message:
`Failed to send notification via shoutrrr (url=slack://watchtower@token-a/token-b/token-c):  message exceeds max length`

**To Reproduce**
This is my docker-compose.yml which fails to do so:
```version: '3.7'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    command: --cleanup --schedule "0 0 0 * * 1"
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=slack://watchtower@token-a/token-b/token-c
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#monitoring
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=":whale:"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Expected behavior**
A notification should be sent to slack since ~1700 < 40,000 chars

**Environment**
 - Platform
 `Ubuntu 20.04`
 - Architecture
 ```Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           113
Model name:                      AMD Ryzen 7 3700X 8-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2193.650
CPU max MHz:                     3600.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7186.68
Virtualization:                  AMD-V
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-15
```
 - Docker version 
```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0```

### LINKED ISSUE #792: MS Teams with different webhook domain
Currently it forces the URL of a webhook to start with `https://outlook.office.com/webhook/`:
https://github.com/containrrr/watchtower/blob/aa3ed8833f484b3c016f8c76260442b1487a91c4/pkg/notifications/msteams.go#L48

A new webhook I created starts with (company name replaced, token removed) 
``` 
https://mycompany.webhook.office.com/webhookb2/...
```

It does not send any notification with the following error in the log:

```
Failed to send notification via shoutrrr (url=teams://%22https%3A:@mycompany.webhook.office.com):  failed to send notification to teams, response status code 404 Not Found
```

### LINKED ISSUE #795: Gotify notifications fail when gotify url contains path
My setup is as follows:

```
WATCHTOWER_NOTIFICATIONS=gotify
WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://example.org/gotify
WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=aToken
```
Since upgrade to 1.1.6, container fails to start with:
```
time="2021-01-24T22:09:39+02:00" level=fatal msg="Failed to initialize Shoutrrr notifications: error initializing router services: parse \"gotify://example.org%2Fgotify/aToken\": invalid URL escape \"%2F\"\n"
```

I suspect this is related to https://github.com/containrrr/watchtower/commit/35490c853d95f9ead6799bd2a16c991a0e1a0ddf

### LINKED ISSUE #797: SMTP Notification fail with error enabling StartTLS: x509: certificate is not valid for any names
**Describe the bug**
Since version 1.1.6, email notifications sent to internal (insecure) SMTP relay fail with error message:
`Failed to send notification via shoutrrr (url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No):  error enabling StartTLS: x509: certificate is not valid for any names, but wanted to match mail.my-domain.com`

**To Reproduce**
Configure Watchtower to send notifications to internal SMTP relay (no Authentication, no TLS, no Certificate):
```
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtover-node1@my-domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=admin@my-domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.my-domain.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=true
```
Trigger notification
Watchtower attempts to send email and fails with error message:
`Failed to send notification via shoutrrr (url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No):  error enabling StartTLS: x509: certificate is not valid for any names, but wanted to match mail.my-domain.com`

**Expected behavior**
Expectation would be that notifications would be sent to the internal SMTP relay. This was working on version 1.1.5.

**Environment**
Ubuntu 20.04.1 LTS
docker-compose version 1.25.0
Docker version 19.03.8, build afacb8b7f0

**Additional context**
The SMTP relay is a postfix instance running on a Synology NAS. It is internal and does not require Authentication nor TLS.

When looking at the SMTP url:
`environment : url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=Yes&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No`
I can see that `starttls=Yes` is forced.

I wonder if it would help to add an additional parameter  to completely disable TLS. 
For example : `WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_DISABLE=true`
This would completely disable TLS and result in the following SMTP url:
`environment : url=smtp://:@mail.my-domain.com:25/?auth=None&encryption=None&fromaddress=watchtover-node1@my-domain.com&fromname=Watchtower&starttls=No&subject=Watchtower updates on watchtover&toaddresses=admin@my-domain.com&usehtml=No`

However, as mentioned, notifications to my internal SMTP relay were working fine in v1.1.5. It stopped working after watchtower was updated to 1.1.6.

**Temporary Fix**
Downgrading back to v1.1.5 resolves this for now.

### PR DESCRIPTION
**Pull request by piksel**
Fixes #797 
Fixes #767 
Fixes #795 
Fixes #792 
Fixes #785 
Fixes #775 
Fixes #772 
Fixes #768 
Fixes #758 
Fixes #761

### CODE REVIEW

**Review by simonaronsson — APPROVED** [review]

**Comment by nrgbistro** [comment]
I'm still having the issue discussed in #768. Previously, I've been using the slack notification service but after finding #768 I converted to shoutrrr. My discord output is still not formatted, it just outputs the same plain text as it did before. Do I need to change something in the shoutrrr notification template to achieve the desired result in #768?

**Comment by simonaronsson** [comment]
> I'm still having the issue discussed in #768. Previously, I've been using the slack notification service but after finding #768 I converted to shoutrrr. My discord output is still not formatted, it just outputs the same plain text as it did before. Do I need to change something in the shoutrrr notification template to achieve the desired result in #768?

Hey,

This has not been released yet. We're looking to do a release real soon however, which should fix this for you.

Best,
Simme

**Comment by nrgbistro** [comment]
Oh my bad. I'm not every experienced with Github just yet. Does this mean after it is merged the formatting issue will be addressed without me having to change my shoutrrr command?

**Comment by simonaronsson** [comment]
Yes, it should IIRC. @piksel might be able to verify. I just released v1.2.0, which should contain this fix for you.

**Comment by nrgbistro** [comment]
I just tried updating and I seem to be getting this error message: `standard_init_linux.go:219: exec user process caused: no such file or directory`. Should I post a separate issue about this?

**Comment by tombomb** [comment]
> I just tried updating and I seem to be getting this error message: `standard_init_linux.go:219: exec user process caused: no such file or directory`. Should I post a separate issue about this?

This is related to https://github.com/containrrr/watchtower/issues/863 they just pushed a new fix for it but I'm now getting 400 errors on my webbooks I'm working on posting a bug report for it.

**Comment by piksel** [comment]
@nrgbistro now with v1.2.1 released it should work, except that the title needs to be added to your discord URL. It should be set automatically by watchtower, but it doesn't right now. 
Just append `?title=Watchtower` to the end of your URL

**Comment by nrgbistro** [comment]
I appended that to my URL but now I have been getting this error message: `Failed to send notification via shoutrrr
url=discord://4dFber9awAMDUhcwWXdgunrN6cPP-------------------------------------@6751095------------?title=Watchtower):  failed to send discord notification: response status code 404 Not Found`

If I try without `?title=Watchtower`, this is the error: `Failed to send notification via shoutrrr (url=discord://4dFber9awAMDUhcwWXdgunrN6c---------------------------------@67510950--------------):  failed to send discord notification: response status code 400 Bad Request`

**Comment by piksel** [comment]
I think something is wrong with your channel number, 404 is usually sent when the channel doesn't exist. 400 is the error I were talking about earlier and is due to a shoutrrrr bug (https://github.com/containrrr/shoutrrr/issues/150).

**Comment by nrgbistro** [comment]
Yeah it looks like I used the wrong channel ID. When I paste the webhook link from Discord into my browser the correct number to use is called `id` and NOT `channel_id`, which is a bit confusing when referring to the watchtower documentation. Everything seems to work correctly now when I append `?title=Watchtower`. Thanks for the support and continued improvements!

**Comment by piksel** [comment]
Yeah, I think the Channel ID is supposed to be called Webhook ID, as that is what it's named in the docs: https://containrrr.dev/shoutrrr/services/discord/ 
and also in https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by nrgbistro** [comment]
Got it! I was using the watchtower documentation instead and it wasn't as clear there but it would have made more sense to check shoutrrr docs.

**Pull request merged**
