### PR TITLE
Add argument to delete volumes on container remove

### LINKED ISSUE #190: Update volumes
My stack is composed by two services: app, which has my application's content and nginx, the webserver.

The nginx service has access to my app's content through a shared volume. The thing is, when watchtower sees a new version for my app, it creates a new container using the new image, as expected. The problem is that the shared volume remains with the old version of my application's content.

Is there a way to configure watchtower to recreate both container and its volume?

### PR DESCRIPTION
**Pull request by zoispag**
Adds a boolean `--remove-volumes` argument to delete volumes on container remove.

Closes #190

Bear with me! This is my first attempt on Go code.
If you find issues, please point me to the correct direction on how to improve this PR.

Thanks

### CODE REVIEW

**Comment by zoispag** [comment]
If this is the correct output of the tests, 0 have failed:



```
go test ./... -v
?   	github.com/containrrr/watchtower	[no test files]
=== RUN   TestActions
Running Suite: Actions Suite
============================
Random Seed: 1560452316
Will run 5 of 5 specs

••time="2019-06-13T20:58:39+02:00" level=info msg="Found multiple running watchtower instances. Cleaning up."
•time="2019-06-13T20:58:40+02:00" level=info msg="Found multiple running watchtower instances. Cleaning up."
•time="2019-06-13T20:58:41+02:00" level=info msg="Found multiple running watchtower instances. Cleaning up."
•
Ran 5 of 5 Specs in 5.018 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestActions (5.02s)
PASS
ok  	github.com/containrrr/watchtower/actions	(cached)
?   	github.com/containrrr/watchtower/app	[no test files]
=== RUN   TestContainer
Running Suite: Container Suite
==============================
Random Seed: 1560452316
Will run 20 of 20 specs

•time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/containers.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_stopped.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image02.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_running.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image01.json
•time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/containers.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_stopped.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image02.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_running.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image01.json
•time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/containers.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_stopped.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image02.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_running.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image01.json
•time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/containers.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_stopped.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image02.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/container_running.json
time="2019-06-13T20:58:36+02:00" level=error msg=~/Projects/watchtower_fork/container/mocks/data/image01.json
••••••••••••••••
Ran 20 of 20 Specs in 0.014 seconds
SUCCESS! -- 20 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestContainer (0.01s)
=== RUN   TestWatchtowerContainersFilter
--- PASS: TestWatchtowerContainersFilter (0.00s)
    filters_test.go:17: PASS:	IsWatchtower()
=== RUN   TestNoFilter
--- PASS: TestNoFilter (0.00s)
=== RUN   TestFilterByNames
--- PASS: TestFilterByNames (0.00s)
    filters_test.go:42: PASS:	Name()
    filters_test.go:47: PASS:	Name()
=== RUN   TestFilterByEnableLabel
--- PASS: TestFilterByEnableLabel (0.00s)
    filters_test.go:57: PASS:	Enabled()
    filters_test.go:62: PASS:	Enabled()
    filters_test.go:67: PASS:	Enabled()
=== RUN   TestFilterByDisabledLabel
--- PASS: TestFilterByDisabledLabel (0.00s)
    filters_test.go:77: PASS:	Enabled()
    filters_test.go:82: PASS:	Enabled()
    filters_test.go:87: PASS:	Enabled()
=== RUN   TestBuildFilter
--- PASS: TestBuildFilter (0.00s)
    filters_test.go:100: PASS:	Name()
    filters_test.go:100: PASS:	Enabled()
    filters_test.go:106: PASS:	Name()
    filters_test.go:106: PASS:	Enabled()
    filters_test.go:112: PASS:	Name()
    filters_test.go:112: PASS:	Enabled()
    filters_test.go:118: PASS:	Name()
    filters_test.go:118: PASS:	Enabled()
    filters_test.go:123: PASS:	Enabled()
=== RUN   TestBuildFilterEnableLabel
--- PASS: TestBuildFilterEnableLabel (0.00s)
    filters_test.go:135: PASS:	Enabled()
    filters_test.go:141: PASS:	Name()
    filters_test.go:141: PASS:	Enabled()
    filters_test.go:147: PASS:	Name()
    filters_test.go:147: PASS:	Enabled()
    filters_test.go:152: PASS:	Enabled()
=== RUN   TestEncodedEnvAuth_ShouldReturnAnErrorIfRepoEnvsAreUnset
--- PASS: TestEncodedEnvAuth_ShouldReturnAnErrorIfRepoEnvsAreUnset (0.00s)
=== RUN   TestEncodedEnvAuth_ShouldReturnAuthHashIfRepoEnvsAreSet
--- PASS: TestEncodedEnvAuth_ShouldReturnAuthHashIfRepoEnvsAreSet (0.00s)
=== RUN   TestEncodedConfigAuth_ShouldReturnAnErrorIfFileIsNotPresent
time="2019-06-13T20:58:36+02:00" level=error msg="Unable to find default config file /dev/null/should-fail/config.json: stat /dev/null/should-fail/config.json: not a directory"
--- PASS: TestEncodedConfigAuth_ShouldReturnAnErrorIfFileIsNotPresent (0.00s)
=== RUN   TestParseServerAddress_ShouldReturnErrorIfPassedEmptyString
--- PASS: TestParseServerAddress_ShouldReturnErrorIfPassedEmptyString (0.00s)
=== RUN   TestParseServerAddress_ShouldReturnTheRepoNameIfPassedAFullyQualifiedImageName
--- PASS: TestParseServerAddress_ShouldReturnTheRepoNameIfPassedAFullyQualifiedImageName (0.00s)
=== RUN   TestParseServerAddress_ShouldReturnTheOrganizationPartIfPassedAnImageNameMissingServerName
--- PASS: TestParseServerAddress_ShouldReturnTheOrganizationPartIfPassedAnImageNameMissingServerName (0.00s)
=== RUN   TestParseServerAddress_ShouldReturnTheServerNameIfPassedAFullyQualifiedImageName
--- PASS: TestParseServerAddress_ShouldReturnTheServerNameIfPassedAFullyQualifiedImageName (0.00s)
=== RUN   TestSliceEqual_True
--- PASS: TestSliceEqual_True (0.00s)
=== RUN   TestSliceEqual_DifferentLengths
--- PASS: TestSliceEqual_DifferentLengths (0.00s)
=== RUN   TestSliceEqual_DifferentContents
--- PASS: TestSliceEqual_DifferentContents (0.00s)
=== RUN   TestSliceSubtract
--- PASS: TestSliceSubtract (0.00s)
=== RUN   TestStringMapSubtract
--- PASS: TestStringMapSubtract (0.00s)
=== RUN   TestStructMapSubtract
--- PASS: TestStructMapSubtract (0.00s)
PASS
ok  	github.com/containrrr/watchtower/container	(cached)
?   	github.com/containrrr/watchtower/container/mocks	[no test files]
?   	github.com/containrrr/watchtower/notifications	[no test files]
```

**Review by simonaronsson — CHANGES_REQUESTED** [review]
Thanks a bunch for contributing! Really appreciate it.
Looks really good. If you dont mind, I'd appreciate if you'd add a test case for the new option as well.

Thanks again 🙏

**Comment by simonaronsson** [comment]
@all-contributors add @zoispag for code

**Comment by simskij** [comment]
resolves #190

**Comment by zoispag** [comment]
@simskij I certainly don't mind! I will take a look to figure out exactly how. If I encounter any issue I will let you know! 🙏

Cheers!

**Comment by simonaronsson** [comment]
Hi again @zoispag,

Can I assist You in any way to get this out the door?

Thanks again,
Simon

**Comment by zoispag** [comment]
Hi @simskij,

i tried to add a new test case, but i stumbled upon some issues with the mockClient and how to mount volume in a mock container :(

This was some time ago and since then I didn't have too much spare time to work on this.
So helping with the test would be highly appreciated.

Thanks,
Zois

**Comment by zoispag** [comment]
@simskij I updated the branch and resolved the conflicts.
Still no progress with the tests though!

**Review by simonaronsson — APPROVED** [review]

**Pull request merged**
