### PR TITLE
Feature/456 Control memory usage of containers

### PR DESCRIPTION
**Pull request by touramakan**
Implementation of the feature request https://github.com/containrrr/watchtower/issues/456

### CODE REVIEW

**Comment by simonaronsson** [comment]
Hey! Thnk you for your contribution! I just wanted to let you know that I have not forgot about you, just been short on time. A review is coming as soon as possible :)

**Comment by touramakan** [comment]
> Hey! Thnk you for your contribution! I just wanted to let you know that I have not forgot about you, just been short on time. A review is coming as soon as possible :)

No problem. I´ve just realised, that I need to rework a bit my solution. I´ll let you know, when I am done.

**Comment by simonaronsson** [comment]
I've since had some time to go through your changes, and while I do appreciate your effort **a lot** I'm having a bit of a hard time understanding why the changes are needed.

Isn't this behavior already controlled by the docker flag `--memory`? In that case, I think it would be preferable to avoid duplicating the effort by adding similar control mechanics to watchtower as well. 

What I'm trying to say is; can you elaborate a bit on why this is needed in watchtower as my immediate reaction that it is a bit out of scope?

Thanks 🙏🏼

**Comment by touramakan** [comment]
> I've since had some time to go through your changes, and while I do appreciate your effort **a lot** I'm having a bit of a hard time understanding why the changes are needed.
> 
> Isn't this behavior already controlled by the docker flag `--memory`? In that case, I think it would be preferable to avoid duplicating the effort by adding similar control mechanics to watchtower as well.
> 
> What I'm trying to say is; can you elaborate a bit on why this is needed in watchtower as my immediate reaction that it is a bit out of scope?
> 
> Thanks 🙏🏼

hey, thanks for your thoughts, which are totally understandable for me.
Indeed, this behavior can be controlled by the docker flag `--memory`.  And this works fine for an end-user, which wants to control the memory usage of his container.
But as a platform provider having multiple consumers sharing a physical memory, it is important on runtime to check and control the memory consumption of the containers and if needed to limit that.

The key point is, developers may omit or misuse the docker flag, that can cause the whole platform to not perform correctly (Out Of Memory).

Since we are using watchtower to provide auto update of image, we thought it would make sense to use it for controlling the memory consumption with the filter ability. 

I think, other PaaS Providers do face the same issue.

Cheers,

**Comment by simonaronsson** [comment]
> > I've since had some time to go through your changes, and while I do appreciate your effort **a lot** I'm having a bit of a hard time understanding why the changes are needed.
> > Isn't this behavior already controlled by the docker flag `--memory`? In that case, I think it would be preferable to avoid duplicating the effort by adding similar control mechanics to watchtower as well.
> > What I'm trying to say is; can you elaborate a bit on why this is needed in watchtower as my immediate reaction that it is a bit out of scope?
> > Thanks 🙏🏼
> 
> hey, thanks for your thoughts, which are totally understandable for me.
> Indeed, this behavior can be controlled by the docker flag `--memory`. And this works fine for an end-user, which wants to control the memory usage of his container.
> But as a platform provider having multiple consumers sharing a physical memory, it is important on runtime to check and control the memory consumption of the containers and if needed to limit that.
> 
> The key point is, developers may omit or misuse the docker flag, that can cause the whole platform to not perform correctly (Out Of Memory).
> 
> Since we are using watchtower to provide auto update of image, we thought it would make sense to use it for controlling the memory consumption with the filter ability.
> 
> I think, other PaaS Providers do face the same issue.
> 
> Cheers,

Got it, thanks. Unfortunately, I don't really think it fits within the scope of the project. I'd recommend that you set up a separate small go binary to do those checks for you, or maintain that feature in a fork. To me, it sounds very much like a restriction you should enforce during creation rather than by restarting containers during runtime.

The use case of watchtower is quite clear, and I'd prefer not to alter that at this point but focus on providing the best experience possible for that.

Thank you for understanding, and hope you find a reasonable way forward. 🙏

**Pull request closed without merging**
